# Generated by Django 4.2 on 2024-04-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_event_slug_alter_event_id_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
