# Generated by Django 4.2 on 2024-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0003_alter_event_date_from_alter_event_date_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='Location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='active',
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('AC', 'Aktiv'), ('IA', 'Inaktiv'), ('CA', 'Abgesagt'), ('SO', 'Ausverkauft')], default='IA', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
