# Generated by Django 4.2 on 2024-05-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='street_number',
        ),
    ]
