# Generated by Django 4.2 on 2024-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0007_alter_profile_city_alter_profile_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
