# Generated by Django 4.2 on 2024-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0008_alter_profile_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
