# Generated by Django 4.2 on 2024-05-04 07:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0013_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['id']),
        ),
    ]
