# Generated by Django 4.2 on 2024-05-04 07:42

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0014_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
