# Generated by Django 4.2 on 2024-05-04 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketApp', '0015_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=999.99, max_digits=5),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ticketApp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
